using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace TestForumServer.Domian.Entities.ForumEntities.Base
{
    /// <summary>
    /// Abstract base class for all entities, providing a unique identifier (Id).
    /// </summary>
    public abstract class Entity
    {
        /// <summary>
        /// Gets or sets the unique identifier for the entity.
        /// This value is automatically generated by the database upon insertion.
        /// </summary>
        [Required]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
}
